-- AlterTable
ALTER TABLE "User" ALTER COLUMN "wins" SET DEFAULT 0,
ALTER COLUMN "wins" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "losses" SET DEFAULT 0,
ALTER COLUMN "losses" SET DATA TYPE DECIMAL(65,30);
