import type { Metadata } from "next";
import "./globals.css";
import Navbar from  "@/src/components/ui/navbar";
import Footer from "../components/ui/footer";
export const metadata: Metadata = {
  title: "code-bout",
  description: "Generated by create-prisma",
};
import { Provider } from "./provider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { 
  return (
    <html lang="en">
      <body className="bg-[#0A0A0F] text-[#F0EFF4] min-h-screen font-sans">

        <div className="absolute inset-0 pointer-events-none"
          style={{ background: "radial-gradient(ellipse 60% 50% at 50% 0%, rgba(230,57,70,0.12), transparent 70%)" }}
        />
        <Navbar />
        <main className="pt-14">
          <Provider>{children}</Provider>
        </main>
        <Footer />
      </body>
    </html>
  );
}
