import type { Metadata } from "next";
// import "./globals.css";
import { Provider } from "./provider";
export const metadata: Metadata = {
  title: "code-bout",
  description: "Generated by create-prisma",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body><Provider>{children}</Provider></body>
    </html>
  );
}
